#!/bin/bash
VERSION=0.1.2
if which pacaur >/dev/null; then
	AUR="pacaur"
else
	AUR="pacman"
fi
case $1 in
    "version")
		echo "aur helper version ${VERSION}"
		;;
    "clear" | "clean")
		$AUR -Sc
		;;
    "ls" | "list" | "freeze")
		$AUR -Q
		;;
    "up" | "upgrade" | "update")
		$AUR -Suy
		;;
    "search")
		shift
		$AUR -Ss $@
		;;
    "install")
		shift
		$AUR -S $@
		;;
    "rm" | "remove" | "delete")
		shift
		$AUR -R $@
		;;
    "info")
		shift
		$AUR -Si $@
		;;
    "bin_refresh")
		shift
		sudo curl -L "https://raw.githubusercontent.com/avelino/aur/master/aur" -o /usr/local/bin/aur && \
		sudo chmod +x /usr/local/bin/aur
		;;
    *)
		$AUR $@
		;;
esac
