#!/bin/bash
VERSION=0.1.4
if which pacaur >/dev/null; then
    AUR="pacaur"
else
    AUR="pacman"
fi
case $1 in
    "version")
	shift
	echo "aur helper version ${VERSION}"
	;;
    "clear" | "clean")
	shift
	$AUR -Sc
	;;
    "ls" | "list" | "freeze")
	shift
	$AUR -Q
	;;
    "up" | "upgrade" | "update")
	shift
	$AUR -Suy
	;;
    "search")
	shift
	$AUR -Ss $@
		;;
    "install")
	shift
	$AUR -S $@
	;;
    "rm" | "remove" | "delete" | "uninstall")
	shift
	$AUR -R $@
	;;
    "info")
	shift
	$AUR -Si $@
	;;
    "orphans")
	shift
	$AUR -Qtdq
	;;
    "optimize")
	shift
	sudo pacman-optimize
	;;
    "deps" | "dependencies")
	shift
	$AUR -Si $@ | awk -F'[:<=>]' '/^Depends/ {print $2}' | xargs -n1 | sort -u
	;;
    "changelog")
	shift
	$AUR -Qc $@
	;;
    "bin_refresh")
	shift
	if which sudo >/dev/null && which curl >/dev/null; then
	    sudo curl -L "https://raw.githubusercontent.com/avelino/aur/master/aur" -o /usr/local/bin/aur
	    sudo chmod +x /usr/local/bin/aur
	else
	    echo "The package sudo or curl is not installed"
	fi
	;;
    *)
	shift
	$AUR $@
	;;
esac
