name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: pacman-repo-builder/action@0.0.0-rc.47
      name: Testing Running on ArchLinux
      with:
        command: ./test_aur.sh
