name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: archlinux
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Install Archlinux
      run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
    - name: Testing Running
      run: ./test_aur.sh
