name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Testing Running
      run: ./test_aur.sh
