name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Testing Running
      run: |
        echo "Testing running"
        apt-get update && apt-get upgrade -y && apt-get install -y pacman
        ./test_aur.sh
