name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: uraimo/run-on-arch-action@v2.0.5
      name: Active ArchLinux
      with:
        arch: armv7
        distro: ubuntu18.04
        run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
    - name: Testing running
      run: ./test_aur.sh
